import type { SecurityOrganization } from "../../data/types";

export const defaultFormValues: SecurityOrganization = {
  id: "",

  legalForm: "",
  sirenOrSiret: "",
  licenseNumber: "",
  cnapsNumber: "",
  registrationDate: "",
  registeredAddress: "",
  officeAddress: "",
  websiteUrl: "",
  generalEmail: "",
  companyPhoneNumber: "",
  directorFullName: "",
  primaryContactName: "",
  primaryContactEmail: "",
  primaryContactPhone: "",

  kbisUploaded: false,
  licenseUploaded: false,
  rcProInsuranceUploaded: false,
  cnapsAuthorizationUploaded: false,
  bankDetailsProvided: false,
  directorIdCopyProvided: false,
  signedPartnershipAgreement: false,
  additionalCertifications: "",

  serviceAreas: "",
  serviceTypes: [],
  support24_7: false,
  minBookingHours: "",
  mobilizationTimeMinutes: "",
  agentsCount: "",
  languagesSpoken: [],
  hasTeamLeader: false,
  armedPersonnelAllowed: false,
  unarmedPersonnelAllowed: true,
  internationalMissions: false,
  specialRequirements: "",

  hourlyRate: "",
  dailyRate: "",
  nightRate: "",
  eventRate: "",
  executiveProtectionRate: "",
  minimumBookingAmount: "",
  commissionPercent: "",
  paymentTerms: "",
  bankAccountIban: "",
  currency: "EUR",
};
